// Generated by website-builder from design-repo/tokens/ (source: https://www.rubiehq.com/). Tailwind v3. Do not hand-edit; re-run the scrape.
// Values are measured from computed styles; names are heuristic. Nothing here overrides Tailwind's default scales.
// Breakpoints: bp-<px> = min-width, bp-max-<px> = max-width (measured from the site's CSS media queries).
export default {
  corePlugins: { preflight: false }, // the site's own CSS is the reset
  "content": [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx,html}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "neutral-01": "rgb(2,6,24)",
        "blue-01": "rgb(187,194,204)",
        "blue-02": "rgb(219,223,229)",
        "neutral-02": "rgb(255,255,255)",
        "neutral-03": "rgb(0,10,39)",
        "neutral-04": "rgb(121,129,141)",
        "neutral-05": "rgb(60,66,74)",
        "blue-03": "rgb(16,102,241)",
        "neutral-06": "rgb(93,100,110)",
        "neutral-07": "rgb(17,16,41)",
        "neutral-08": "rgb(248,249,252)",
        "blue-04": "rgb(231,234,238)",
        "blue-05": "rgb(47,50,69)",
        "neutral-09": "rgb(102,102,102)",
        "neutral-10": "rgb(0,3,10)",
        "blue-06": "rgb(227,231,235)",
        "neutral-11": "rgb(10,10,10)",
        "blue-07": "rgb(2,99,255)",
        "blue-08": "rgb(223,227,232)",
        "neutral-12": "rgb(0,0,0)",
        "blue-09": "rgb(13,95,226)",
        "neutral-13": "rgb(238,241,245)",
        "neutral-14": "rgba(5,35,52,0.07)",
        "blue-10": "rgb(170,179,191)",
        "blue-11": "rgb(48,122,243)",
        "blue-12": "rgb(77,140,249)",
        "neutral-15": "rgb(248,249,250)",
        "neutral-16": "rgb(230,239,254)",
        "blue-13": "rgb(209,213,220)",
        "neutral-17": "rgb(229,229,229)",
        "blue-14": "rgb(130,175,251)",
        "neutral-18": "rgb(248,250,252)",
        "neutral-19": "rgb(135,142,153)",
        "blue-15": "rgb(41,118,242)",
        "neutral-20": "rgb(163,171,182)",
        "blue-16": "rgb(214,219,225)",
        "neutral-21": "rgba(255,255,255,0.24)",
        "neutral-22": "rgb(245,247,250)",
        "neutral-23": "rgba(255,255,255,0.15)",
        "blue-17": "rgb(180,207,253)",
        "neutral-24": "rgba(255,255,255,0.22)",
        "neutral-25": "rgba(255,255,255,0.82)",
        "neutral-26": "rgb(153,153,153)",
        "blue-18": "rgb(215,221,228)",
        "neutral-27": "rgb(238,241,244)",
        "neutral-28": "rgb(252,253,254)",
        "blue-19": "rgb(4,53,133)",
        "neutral-29": "rgba(255,255,255,0.2)",
        "blue-20": "rgb(184,192,202)",
        "blue-21": "rgb(197,204,213)",
        "neutral-30": "rgb(217,217,217)",
        "blue-22": "rgb(9,77,185)",
        "neutral-31": "rgba(255,255,255,0.18)",
        "surface-default": "rgb(248,249,252)",
        "surface-alt": "rgb(255,255,255)",
        "surface-inverse": "rgb(0,10,39)",
        "surface-accent": "rgb(2,99,255)",
        "text-primary": "rgb(2,6,24)",
        "text-secondary": "rgb(0,10,39)",
        "text-inverse": "rgb(187,194,204)",
        "text-accent": "rgb(16,102,241)",
        "border-default": "rgb(231,234,238)",
        "accent-primary": "rgb(16,102,241)"
      },
      "spacing": {
        "sp-2": "2px",
        "sp-4": "4px",
        "sp-6": "6px",
        "sp-8": "8px",
        "sp-9": "9px",
        "sp-10": "10px",
        "sp-12": "12px",
        "sp-16": "16px",
        "sp-20": "20px",
        "sp-24": "24px",
        "sp-28": "28px",
        "sp-32": "32px",
        "sp-36": "36px",
        "sp-40": "40px",
        "sp-48": "48px",
        "sp-56": "56px",
        "sp-64": "64px",
        "sp-80": "80px",
        "sp-88": "88px",
        "sp-90": "90px",
        "sp-96": "96px",
        "sp-100": "100px",
        "sp-112": "112px",
        "sp-128": "128px",
        "gutter": "8px"
      },
      "borderRadius": {
        "r-8": "8px",
        "r-16": "16px",
        "r-10": "10px",
        "r-24": "24px",
        "r-12": "12px",
        "r-7": "7px",
        "surface": "8px"
      },
      "boxShadow": {
        "e-01": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(16, 102, 241, 0.05) 0px 12px 12px -6px, rgba(16, 102, 241, 0.05) 0px 8px 8px -4px, rgba(16, 102, 241, 0.05) 0px 6px 6px -3px, rgba(16, 102, 241, 0.05) 0px 4px 4px -2px",
        "e-02": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(255, 255, 255, 0.5) 0px 0px 4px 0px inset, rgba(255, 255, 255, 0.2) 0px 0px 8px 0px inset",
        "e-03": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgb(227, 231, 235) 0px 0px 0px 1px",
        "e-04": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 10, 39, 0.04) 0px 0px 0px 1px, rgba(0, 10, 39, 0.02) 0px 1px 2px 0px, rgba(0, 10, 39, 0.02) 0px 2px 4px 0px, rgba(0, 10, 39, 0.02) 0px 8px 16px 0px, rgba(0, 10, 39, 0.03) 0px 32px 44px -12px",
        "e-05": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(14, 43, 79, 0.08) 0px 40px 40px -20px, rgba(14, 43, 79, 0.08) 0px 24px 24px -12px, rgba(14, 43, 79, 0.08) 0px 12px 12px -6px, rgba(14, 43, 79, 0.08) 0px 4px 4px -2px, rgba(15, 45, 85, 0.06) 0px 0px 0px 1px",
        "e-06": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(255, 255, 255, 0.5) 0px 0px 4px 0px inset, rgba(255, 255, 255, 0.2) 0px 0px 8px 0px inset, rgba(16, 102, 241, 0.05) 0px 12px 12px -6px, rgba(16, 102, 241, 0.05) 0px 8px 8px -4px, rgba(16, 102, 241, 0.05) 0px 6px 6px -3px, rgba(16, 102, 241, 0.05) 0px 4px 4px -2px",
        "e-07": "rgba(0, 39, 80, 0.06) 0px 4px 12px 0px, rgba(0, 39, 80, 0.06) 0px 4px 4px -2px",
        "e-08": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(255, 255, 255, 0.35) 0px 0px 0px 1px inset",
        "elev-default": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(16, 102, 241, 0.05) 0px 12px 12px -6px, rgba(16, 102, 241, 0.05) 0px 8px 8px -4px, rgba(16, 102, 241, 0.05) 0px 6px 6px -3px, rgba(16, 102, 241, 0.05) 0px 4px 4px -2px"
      },
      "fontFamily": {
        "ff-01": [
          "\"Geist\"",
          "sans-serif"
        ],
        "ff-02": [
          "ui-monospace",
          "sans-serif"
        ],
        "ff-03": [
          "system-ui",
          "sans-serif"
        ],
        "display": [
          "\"Geist\"",
          "sans-serif"
        ],
        "heading": [
          "\"Geist\"",
          "sans-serif"
        ],
        "body": [
          "\"Geist\"",
          "sans-serif"
        ],
        "label": [
          "\"Geist\"",
          "sans-serif"
        ]
      },
      "fontSize": {
        "fs-11": "11px",
        "fs-12": "12px",
        "fs-13": "13px",
        "fs-14": "14px",
        "fs-16": "16px",
        "fs-18": "18px",
        "fs-20": "20px",
        "fs-24": "24px",
        "fs-25": "25px",
        "fs-26": "26px",
        "fs-30": "30px",
        "fs-36": "36px",
        "fs-40": "40px",
        "fs-42": "42px",
        "fs-44": "44px",
        "fs-48": "48px",
        "fs-52": "52px",
        "fs-60": "60px",
        "display": [
          "52px",
          {
            "lineHeight": "54.6px",
            "fontWeight": "600"
          }
        ],
        "heading": [
          "14px",
          {
            "lineHeight": "20px",
            "fontWeight": "400"
          }
        ],
        "body": [
          "14px",
          {
            "lineHeight": "24px",
            "fontWeight": "500"
          }
        ],
        "label": [
          "14px",
          {
            "lineHeight": "20px",
            "fontWeight": "400"
          }
        ]
      },
      "transitionDuration": {
        "d-150ms": "0.15s",
        "d-200ms": "0.2s",
        "d-80ms": "0.08s",
        "d-1400ms": "1.4s",
        "d-300ms": "0.3s",
        "d-500ms": "0.5s",
        "d-90000ms": "90s",
        "d-34000ms": "34s",
        "motion-default": "0.15s"
      },
      "transitionTimingFunction": {
        "ease-01": "cubic-bezier(0.4, 0, 0.2, 1)",
        "ease-02": "linear",
        "ease-03": "ease-out",
        "ease-04": "cubic-bezier(0.34, 1.56, 0.64, 1)",
        "ease-05": "cubic-bezier(0.16, 1, 0.3, 1)",
        "motion-default": "cubic-bezier(0.4, 0, 0.2, 1)"
      },
      "screens": {
        "bp-400": {
          "min": "400px"
        },
        "bp-420": {
          "min": "420px"
        },
        "bp-640": {
          "min": "640px"
        },
        "bp-768": {
          "min": "768px"
        },
        "bp-1024": {
          "min": "1024px"
        },
        "bp-1280": {
          "min": "1280px"
        },
        "bp-1350": {
          "min": "1350px"
        },
        "bp-1536": {
          "min": "1536px"
        },
        "bp-max-640": {
          "max": "640px"
        },
        "bp-max-480": {
          "max": "480px"
        }
      },
      "maxWidth": {
        "content": "1440px"
      }
    }
  },
  "plugins": []
};
